spring:
  application:
    name: spring-fhir-starter

management:
  endpoints:
    web:
      base-path: /actuator
      path-mapping:
        health: health
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus

  observations:
    annotations:
      enabled: true

  metrics:
    enable:
      spring.security: false
    distribution:
      percentiles:
        http:
          - 0.99
          - 0.95
          - 0.50
      percentiles-histogram:
        http:
          server.requests: true
          client.requests: true
        spring.data.mongodb.command: true
        osh.conditions: true
        jdbc.query: true
    tags:
      service: ${spring.application.name}

  endpoint:
    health:
      show-details: always

  tracing:
    enabled: true
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      export:
        enabled: true

  opentelemetry:
    resource-attributes: { }

app:
  fhir:
    server: http://hapi.fhir.org/baseR4
